# Generated by Django 4.1.5 on 2023-09-06 11:45

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=posts.models.upload_to, verbose_name='Image'),
        ),
    ]
