# Generated by Django 4.1.5 on 2023-09-06 11:45

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='accounts/default.jpg', upload_to=accounts.models.upload_to, verbose_name='Image'),
        ),
    ]
